//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoletaProy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public boleta()
        {
            this.solucion = new HashSet<solucion>();
        }
    
        public int id { get; set; }
        public int nro_orden { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public System.DateTime hora_inicio { get; set; }
        public Nullable<System.DateTime> hora_asignacion { get; set; }
        public System.DateTime hora_fin { get; set; }
        public string prioridad { get; set; }
        public int id_usr { get; set; }
        public int id_pers { get; set; }
        public int id_serv { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual servicio servicio { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solucion> solucion { get; set; }
    }
}
